### ISSUE TITLE
[RAM] Incorrect unit

### ISSUE THREAD

**Issue by jgrunder** [DBaker85/astern#4]
**Describe the bug**
Used RAM is not showed with the correct unit

**To Reproduce**
No way, it depends on the motherboard I guess

**Expected behavior**
If RAM is received from MoBro sensor with MB unit, convert to GB or show MB unit

**Screenshots**
![2020-11-10_18h20_58](https://user-images.githubusercontent.com/59175963/98708771-d5397d00-2381-11eb-9ca3-514ee3fc6457.png)

**Additional context**
In my point of view, showing amount with MB unit should be better, but the text size must be readapted
See: `MobroSDK.emit("monitor:hardware")` and callbacks `data.memory.capacityunit & data.memory.totalcapacity`

Btw thank you so much for the theme <3

**Comment by DBaker85** [comment]
Interesting result, it seems HWinfo provides sensor data in MB and HWinfo was not tested.
I can fix it so that it gets converted to GB.

As for the MB / GB, I chose GBs as a compromise as it offers better legibility for on small screens.

Could you provide some extra context regarding why MB would be better?

**Comment by jgrunder** [comment]
I don't know, I've always been comfortable reading my RAM in MB, I find it's more accurate even if at my level I don't need so much precision. Maybe someone who only has 4 GB of RAM (yes it still exists ^^) or someone for who it' s important to see it in MB (not me in my gaming context, but I think someone might be interested one day).
In a more global way, why not offer the possibility to customize these elements in a separate configuration file? 
`<param key="ram.unit" value="MB" default="GB" />`

**Comment by DBaker85** [comment]
I see. 
I think the best solution right now would be to use the unit value returned by the sensor.
`Libre Hardware` and `Open Hardware` would return `GB` and show GB on the Display
`HWiNFO` would show `MB`.
I think this is easiest for the average end user rather than providing config files.

**Comment by jgrunder** [comment]
It's up to you, but if you keep it in MB, the 4-digit display takes up too much place in the RAM space. You should probably test the returned unit and adjust the space taken.

**Comment by DBaker85** [comment]
I will split this request into 2 parts.
1 will be the bugfix for the values being returned as MB
I will also open a feature request to consider allowing values between GB and MB 👍

**Comment by jgrunder** [comment]
Thank you for the fix, but please note that to convert MB to GB you must divide by 1024 and not 1000

**Comment by DBaker85** [comment]
Indeed.
It seems I got confused about megabytes vs mebibytes.
That 1GB = 1000MB but not when applied to RAM units.
I will fix it in a later update for other fixes that I have planned.

Closing this for now, thanks for the help and suggestions
