### ISSUE TITLE
[New feature] Add a clock on the theme

### ISSUE THREAD

**Issue by jgrunder** [DBaker85/astern#7]
**Is your feature request related to a problem? Please describe.**
As a gamer user, I would like to see the current time because the game is in fullscreen mode

**Describe the solution you'd like**
Somewhere, discreetly in the screen, see the current time as format HH:MM (24h format)

**Describe alternatives you've considered**
Could be added later with the ability for the user to set custom configuration parameters, let him choose if he wants to display the clock, and if yes what format (12/24h)

**Additional context**
None

**Comment by jgrunder** [comment]
Hi, are you still there ?

**Comment by DBaker85** [comment]
Yes. I have been very busy with a lot of things. This is something I had already considered.
I will be probably releasing a version next year with some improvements and tweaked ui (Im not too good at that, but I try).
This improvement is on my list

**Comment by DBaker85** [comment]
Just released a new version that does have a clock

Fixed in [v1.0.0](https://github.com/DBaker85/astern/releases/tag/1.0.0)
